# -*- coding: utf-8 -*-


import enum


class Op:
    class Mode(enum.Enum):
        NONE = ( 1, 0)
        IM   = ( 2, 1)
        ZP   = ( 3, 1)
        ZPX  = ( 4, 1)
        ZPY  = ( 5, 1)
        AB   = ( 6, 2)
        ABX  = ( 7, 2)
        ABY  = ( 8, 2)
        IX   = ( 9, 1)
        IY   = (10, 1)
        REL  = (11, 1)
        IND  = (12, 2)
        BRK  = (13, 1)

        def __init__(self, id_, argsize):
            self.argsize = argsize

    def __init__(self, code, name, mode, official, argread, argwrite, argexec):
        self.code     = code
        self.name     = name
        self.mode     = mode
        self.official = official

        self.argread  = argread
        self.argwrite = argwrite
        self.argexec  = argexec

    @property
    def argsize(self):
        return self.mode.argsize

    @property
    def size(self):
        return self.mode.argsize + 1

    def __repr__(self):
        return "Op({}, '{}', {}, {})".format(self.code, self.name, self.mode, self.official)

    _OPS = None
    @staticmethod
    def get(code):
        if Op._OPS is None:
            # http://wiki.nesdev.com/w/index.php/CPU_unofficial_opcodes
            # 非公式命令の rwx フラグはあまり自信なし
            # IX, IY, IND の rwx はポインタ自体に対するアクセス(どうせポインタ
            # が指す先はわからないので…)
            Op._OPS = (
                #  code  name   mode          offi   arg_r  arg_w  arg_x
                Op(0x00, "brk", Op.Mode.BRK,  True,  False, False, False),
                Op(0x01, "ora", Op.Mode.IX,   True,  True,  False, False),
                Op(0x02, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x03, "slo", Op.Mode.IX,   False, True,  False, False),
                Op(0x04, "dop", Op.Mode.ZP,   False, True,  False, False),
                Op(0x05, "ora", Op.Mode.ZP,   True,  True,  False, False),
                Op(0x06, "asl", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0x07, "slo", Op.Mode.ZP,   False, True,  True,  False),
                Op(0x08, "php", Op.Mode.NONE, True,  False, False, False),
                Op(0x09, "ora", Op.Mode.IM,   True,  False, False, False),
                Op(0x0A, "asl", Op.Mode.NONE, True,  False, False, False),
                Op(0x0B, "anc", Op.Mode.IM,   False, False, False, False),
                Op(0x0C, "top", Op.Mode.AB,   False, True,  False, False),
                Op(0x0D, "ora", Op.Mode.AB,   True,  True,  False, False),
                Op(0x0E, "asl", Op.Mode.AB,   True,  True,  True,  False),
                Op(0x0F, "slo", Op.Mode.AB,   False, True,  True,  False),
                Op(0x10, "bpl", Op.Mode.REL,  True,  True,  False, True ),
                Op(0x11, "ora", Op.Mode.IY,   True,  True,  False, False),
                Op(0x12, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x13, "slo", Op.Mode.IY,   False, True,  False, False),
                Op(0x14, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0x15, "ora", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0x16, "asl", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0x17, "slo", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0x18, "clc", Op.Mode.NONE, True,  False, False, False),
                Op(0x19, "ora", Op.Mode.ABY,  True,  True,  False, False),
                Op(0x1A, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0x1B, "slo", Op.Mode.ABY,  False, True,  True,  False),
                Op(0x1C, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0x1D, "ora", Op.Mode.ABX,  True,  True,  False, False),
                Op(0x1E, "asl", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0x1F, "slo", Op.Mode.ABX,  False, True,  True,  False),
                Op(0x20, "jsr", Op.Mode.AB,   True,  True,  False, True ),
                Op(0x21, "and", Op.Mode.IX,   True,  True,  False, False),
                Op(0x22, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x23, "rla", Op.Mode.IX,   False, True,  False, False),
                Op(0x24, "bit", Op.Mode.ZP,   True,  True,  False, False),
                Op(0x25, "and", Op.Mode.ZP,   True,  True,  False, False),
                Op(0x26, "rol", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0x27, "rla", Op.Mode.ZP,   False, True,  True,  False),
                Op(0x28, "plp", Op.Mode.NONE, True,  False, False, False),
                Op(0x29, "and", Op.Mode.IM,   True,  False, False, False),
                Op(0x2A, "rol", Op.Mode.NONE, True,  False, False, False),
                Op(0x2B, "anc", Op.Mode.IM,   False, False, False, False),
                Op(0x2C, "bit", Op.Mode.AB,   True,  True,  False, False),
                Op(0x2D, "and", Op.Mode.AB,   True,  True,  False, False),
                Op(0x2E, "rol", Op.Mode.AB,   True,  True,  True,  False),
                Op(0x2F, "rla", Op.Mode.AB,   False, True,  True,  False),
                Op(0x30, "bmi", Op.Mode.REL,  True,  True,  False, True ),
                Op(0x31, "and", Op.Mode.IY,   True,  True,  False, False),
                Op(0x32, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x33, "rla", Op.Mode.IY,   False, True,  False, False),
                Op(0x34, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0x35, "and", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0x36, "rol", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0x37, "rla", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0x38, "sec", Op.Mode.NONE, True,  False, False, False),
                Op(0x39, "and", Op.Mode.ABY,  True,  True,  False, False),
                Op(0x3A, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0x3B, "rla", Op.Mode.ABY,  False, True,  True,  False),
                Op(0x3C, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0x3D, "and", Op.Mode.ABX,  True,  True,  False, False),
                Op(0x3E, "rol", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0x3F, "rla", Op.Mode.ABX,  False, True,  True,  False),
                Op(0x40, "rti", Op.Mode.NONE, True,  False, False, False),
                Op(0x41, "eor", Op.Mode.IX,   True,  True,  False, False),
                Op(0x42, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x43, "sre", Op.Mode.IX,   False, True,  False, False),
                Op(0x44, "dop", Op.Mode.ZP,   False, True,  False, False),
                Op(0x45, "eor", Op.Mode.ZP,   True,  True,  False, False),
                Op(0x46, "lsr", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0x47, "sre", Op.Mode.ZP,   False, True,  True,  False),
                Op(0x48, "pha", Op.Mode.NONE, True,  False, False, False),
                Op(0x49, "eor", Op.Mode.IM,   True,  False, False, False),
                Op(0x4A, "lsr", Op.Mode.NONE, True,  False, False, False),
                Op(0x4B, "alr", Op.Mode.IM,   False, False, False, False),
                Op(0x4C, "jmp", Op.Mode.AB,   True,  True,  False, True ),
                Op(0x4D, "eor", Op.Mode.AB,   True,  True,  False, False),
                Op(0x4E, "lsr", Op.Mode.AB,   True,  True,  True,  False),
                Op(0x4F, "sre", Op.Mode.AB,   False, True,  True,  False),
                Op(0x50, "bvc", Op.Mode.REL,  True,  True,  False, True ),
                Op(0x51, "eor", Op.Mode.IY,   True,  True,  False, False),
                Op(0x52, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x53, "sre", Op.Mode.IY,   False, True,  False, False),
                Op(0x54, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0x55, "eor", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0x56, "lsr", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0x57, "sre", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0x58, "cli", Op.Mode.NONE, True,  False, False, False),
                Op(0x59, "eor", Op.Mode.ABY,  True,  True,  False, False),
                Op(0x5A, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0x5B, "sre", Op.Mode.ABY,  False, True,  True,  False),
                Op(0x5C, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0x5D, "eor", Op.Mode.ABX,  True,  True,  False, False),
                Op(0x5E, "lsr", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0x5F, "sre", Op.Mode.ABX,  False, True,  True,  False),
                Op(0x60, "rts", Op.Mode.NONE, True,  False, False, False),
                Op(0x61, "adc", Op.Mode.IX,   True,  True,  False, False),
                Op(0x62, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x63, "rra", Op.Mode.IX,   False, True,  False, False),
                Op(0x64, "dop", Op.Mode.ZP,   False, True,  False, False),
                Op(0x65, "adc", Op.Mode.ZP,   True,  True,  False, False),
                Op(0x66, "ror", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0x67, "rra", Op.Mode.ZP,   False, True,  True,  False),
                Op(0x68, "pla", Op.Mode.NONE, True,  False, False, False),
                Op(0x69, "adc", Op.Mode.IM,   True,  False, False, False),
                Op(0x6A, "ror", Op.Mode.NONE, True,  False, False, False),
                Op(0x6B, "arr", Op.Mode.IM,   False, False, False, False),
                Op(0x6C, "jmp", Op.Mode.IND,  True,  True,  False, False),
                Op(0x6D, "adc", Op.Mode.AB,   True,  True,  False, False),
                Op(0x6E, "ror", Op.Mode.AB,   True,  True,  True,  False),
                Op(0x6F, "rra", Op.Mode.AB,   False, True,  True,  False),
                Op(0x70, "bvs", Op.Mode.REL,  True,  True,  False, True ),
                Op(0x71, "adc", Op.Mode.IY,   True,  True,  False, False),
                Op(0x72, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x73, "rra", Op.Mode.IY,   False, True,  False, False),
                Op(0x74, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0x75, "adc", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0x76, "ror", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0x77, "rra", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0x78, "sei", Op.Mode.NONE, True,  False, False, False),
                Op(0x79, "adc", Op.Mode.ABY,  True,  True,  False, False),
                Op(0x7A, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0x7B, "rra", Op.Mode.ABY,  False, True,  True,  False),
                Op(0x7C, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0x7D, "adc", Op.Mode.ABX,  True,  True,  False, False),
                Op(0x7E, "ror", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0x7F, "rra", Op.Mode.ABX,  False, True,  True,  False),
                Op(0x80, "dop", Op.Mode.IM,   False, False, False, False),
                Op(0x81, "sta", Op.Mode.IX,   True,  True,  False, False),
                Op(0x82, "dop", Op.Mode.IM,   False, False, False, False),
                Op(0x83, "sax", Op.Mode.IX,   False, True,  False, False),
                Op(0x84, "sty", Op.Mode.ZP,   True,  False, True,  False),
                Op(0x85, "sta", Op.Mode.ZP,   True,  False, True,  False),
                Op(0x86, "stx", Op.Mode.ZP,   True,  False, True,  False),
                Op(0x87, "sax", Op.Mode.ZP,   False, False, True,  False),
                Op(0x88, "dey", Op.Mode.NONE, True,  False, False, False),
                Op(0x89, "dop", Op.Mode.IM,   False, False, False, False),
                Op(0x8A, "txa", Op.Mode.NONE, True,  False, False, False),
                Op(0x8B, "xaa", Op.Mode.IM,   False, False, False, False),
                Op(0x8C, "sty", Op.Mode.AB,   True,  False, True,  False),
                Op(0x8D, "sta", Op.Mode.AB,   True,  False, True,  False),
                Op(0x8E, "stx", Op.Mode.AB,   True,  False, True,  False),
                Op(0x8F, "sax", Op.Mode.AB,   False, False, True,  False),
                Op(0x90, "bcc", Op.Mode.REL,  True,  True,  False, True ),
                Op(0x91, "sta", Op.Mode.IY,   True,  True,  False, False),
                Op(0x92, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0x93, "ahx", Op.Mode.IY,   False, True,  False, False),
                Op(0x94, "sty", Op.Mode.ZPX,  True,  False, True,  False),
                Op(0x95, "sta", Op.Mode.ZPX,  True,  False, True,  False),
                Op(0x96, "stx", Op.Mode.ZPY,  True,  False, True,  False),
                Op(0x97, "sax", Op.Mode.ZPY,  False, False, True,  False),
                Op(0x98, "tya", Op.Mode.NONE, True,  False, False, False),
                Op(0x99, "sta", Op.Mode.ABY,  True,  False, True,  False),
                Op(0x9A, "txs", Op.Mode.NONE, True,  False, False, False),
                Op(0x9B, "tas", Op.Mode.ABY,  False, False, True,  False),
                Op(0x9C, "shy", Op.Mode.ABX,  False, False, True,  False),
                Op(0x9D, "sta", Op.Mode.ABX,  True,  False, True,  False),
                Op(0x9E, "shx", Op.Mode.ABY,  False, False, True,  False),
                Op(0x9F, "ahx", Op.Mode.ABY,  False, False, True,  False),
                Op(0xA0, "ldy", Op.Mode.IM,   True,  False, False, False),
                Op(0xA1, "lda", Op.Mode.IX,   True,  True,  False, False),
                Op(0xA2, "ldx", Op.Mode.IM,   True,  False, False, False),
                Op(0xA3, "lax", Op.Mode.IX,   False, True,  False, False),
                Op(0xA4, "ldy", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xA5, "lda", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xA6, "ldx", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xA7, "lax", Op.Mode.ZP,   False, True,  False, False),
                Op(0xA8, "tay", Op.Mode.NONE, True,  False, False, False),
                Op(0xA9, "lda", Op.Mode.IM,   True,  False, False, False),
                Op(0xAA, "tax", Op.Mode.NONE, True,  False, False, False),
                Op(0xAB, "lax", Op.Mode.IM,   False, False, False, False),
                Op(0xAC, "ldy", Op.Mode.AB,   True,  True,  False, False),
                Op(0xAD, "lda", Op.Mode.AB,   True,  True,  False, False),
                Op(0xAE, "ldx", Op.Mode.AB,   True,  True,  False, False),
                Op(0xAF, "lax", Op.Mode.AB,   False, True,  False, False),
                Op(0xB0, "bcs", Op.Mode.REL,  True,  True,  False, True ),
                Op(0xB1, "lda", Op.Mode.IY,   True,  True,  False, False),
                Op(0xB2, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0xB3, "lax", Op.Mode.IY,   False, True,  False, False),
                Op(0xB4, "ldy", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0xB5, "lda", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0xB6, "ldx", Op.Mode.ZPY,  True,  True,  False, False),
                Op(0xB7, "lax", Op.Mode.ZPY,  False, True,  False, False),
                Op(0xB8, "clv", Op.Mode.NONE, True,  False, False, False),
                Op(0xB9, "lda", Op.Mode.ABY,  True,  True,  False, False),
                Op(0xBA, "tsx", Op.Mode.NONE, True,  False, False, False),
                Op(0xBB, "las", Op.Mode.ABY,  False, True,  True,  False),
                Op(0xBC, "ldy", Op.Mode.ABX,  True,  True,  False, False),
                Op(0xBD, "lda", Op.Mode.ABX,  True,  True,  False, False),
                Op(0xBE, "ldx", Op.Mode.ABY,  True,  True,  False, False),
                Op(0xBF, "lax", Op.Mode.ABY,  False, True,  False, False),
                Op(0xC0, "cpy", Op.Mode.IM,   True,  False, False, False),
                Op(0xC1, "cmp", Op.Mode.IX,   True,  True,  False, False),
                Op(0xC2, "dop", Op.Mode.IM,   False, False, False, False),
                Op(0xC3, "dcp", Op.Mode.IX,   False, True,  False, False),
                Op(0xC4, "cpy", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xC5, "cmp", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xC6, "dec", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0xC7, "dcp", Op.Mode.ZP,   False, True,  True,  False),
                Op(0xC8, "iny", Op.Mode.NONE, True,  False, False, False),
                Op(0xC9, "cmp", Op.Mode.IM,   True,  False, False, False),
                Op(0xCA, "dex", Op.Mode.NONE, True,  False, False, False),
                Op(0xCB, "axs", Op.Mode.IM,   False, False, False, False),
                Op(0xCC, "cpy", Op.Mode.AB,   True,  True,  False, False),
                Op(0xCD, "cmp", Op.Mode.AB,   True,  True,  False, False),
                Op(0xCE, "dec", Op.Mode.AB,   True,  True,  True,  False),
                Op(0xCF, "dcp", Op.Mode.AB,   False, True,  True,  False),
                Op(0xD0, "bne", Op.Mode.REL,  True,  True,  False, True ),
                Op(0xD1, "cmp", Op.Mode.IY,   True,  True,  False, False),
                Op(0xD2, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0xD3, "dcp", Op.Mode.IY,   False, True,  False, False),
                Op(0xD4, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0xD5, "cmp", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0xD6, "dec", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0xD7, "dcp", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0xD8, "cld", Op.Mode.NONE, True,  False, False, False),
                Op(0xD9, "cmp", Op.Mode.ABY,  True,  True,  False, False),
                Op(0xDA, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0xDB, "dcp", Op.Mode.ABY,  False, True,  True,  False),
                Op(0xDC, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0xDD, "cmp", Op.Mode.ABX,  True,  True,  False, False),
                Op(0xDE, "dec", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0xDF, "dcp", Op.Mode.ABX,  False, True,  True,  False),
                Op(0xE0, "cpx", Op.Mode.IM,   True,  False, False, False),
                Op(0xE1, "sbc", Op.Mode.IX,   True,  True,  False, False),
                Op(0xE2, "dop", Op.Mode.IM,   False, False, False, False),
                Op(0xE3, "isc", Op.Mode.IX,   False, True,  False, False),
                Op(0xE4, "cpx", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xE5, "sbc", Op.Mode.ZP,   True,  True,  False, False),
                Op(0xE6, "inc", Op.Mode.ZP,   True,  True,  True,  False),
                Op(0xE7, "isc", Op.Mode.ZP,   False, True,  True,  False),
                Op(0xE8, "inx", Op.Mode.NONE, True,  False, False, False),
                Op(0xE9, "sbc", Op.Mode.IM,   True,  False, False, False),
                Op(0xEA, "nop", Op.Mode.NONE, True,  False, False, False),
                Op(0xEB, "sbc", Op.Mode.IM,   False, False, False, False),
                Op(0xEC, "cpx", Op.Mode.AB,   True,  True,  False, False),
                Op(0xED, "sbc", Op.Mode.AB,   True,  True,  False, False),
                Op(0xEE, "inc", Op.Mode.AB,   True,  True,  True,  False),
                Op(0xEF, "isc", Op.Mode.AB,   False, True,  True,  False),
                Op(0xF0, "beq", Op.Mode.REL,  True,  True,  False, True ),
                Op(0xF1, "sbc", Op.Mode.IY,   True,  True,  False, False),
                Op(0xF2, "kil", Op.Mode.NONE, False, False, False, False),
                Op(0xF3, "isc", Op.Mode.IY,   False, True,  False, False),
                Op(0xF4, "dop", Op.Mode.ZPX,  False, True,  False, False),
                Op(0xF5, "sbc", Op.Mode.ZPX,  True,  True,  False, False),
                Op(0xF6, "inc", Op.Mode.ZPX,  True,  True,  True,  False),
                Op(0xF7, "isc", Op.Mode.ZPX,  False, True,  True,  False),
                Op(0xF8, "sed", Op.Mode.NONE, True,  False, False, False),
                Op(0xF9, "sbc", Op.Mode.ABY,  True,  True,  False, False),
                Op(0xFA, "nop", Op.Mode.NONE, False, False, False, False),
                Op(0xFB, "isc", Op.Mode.ABY,  False, True,  True,  False),
                Op(0xFC, "top", Op.Mode.ABX,  False, True,  False, False),
                Op(0xFD, "sbc", Op.Mode.ABX,  True,  True,  False, False),
                Op(0xFE, "inc", Op.Mode.ABX,  True,  True,  True,  False),
                Op(0xFF, "isc", Op.Mode.ABX,  False, True,  True,  False),
            )
        return Op._OPS[code]
